name: CI Checks

# run this workflow on specific events in github
on:
    # pull requests to master
    pull_request:
        paths:
            - '**'

    # every commit on master
    push:
        branches:
            - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]

    steps:    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
          
      - name: Cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-       
          
          
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
         version: 6.0.2   
         run_install: true
         
      - run: pnpm test
